### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Divido' not found in

### ISSUE THREAD

**Issue by ottybrad** [DividoFinancialServices/divido-magento2#1]
`
Fatal error: Uncaught Error: Class 'Divido' not found in /srv/users/serverpilot/apps/otty-magento/public/app/code/Divido/DividoFinancing/Helper/Data.php:83 Stack trace: #0 /srv/users/serverpilot/apps/otty-magento/public/app/code/Divido/DividoFinancing/Model/Adminhtml/Source/PlanSelection.php(27): Divido\DividoFinancing\Helper\Data->getAllPlans() #1 /srv/users/serverpilot/apps/otty-magento/public/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(453): Divido\DividoFinancing\Model\Adminhtml\Source\PlanSelection->toOptionArray(true) #2 /srv/users/serverpilot/apps/otty-magento/public/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(371): Magento\Config\Model\Config\Structure\Element\Field->_getOptionsFromSourceModel(Object(Divido\DividoFinancing\Model\Adminhtml\Source\PlanSelection)) #3 /srv/users/serverpilot/apps/otty-magento/public/var/generation/Magento/Config/Model/Config/Structure/Element/Field/Interceptor.php(323): Magento\Config\Model\Config\Structure\Element\Field->getOptions() in /srv/users/serverpilot/apps/otty-magento/public/app/code/Divido/DividoFinancing/Helper/Data.php on line 83`

**Comment by cjgk** [comment]
Hi,

What version of Magento 2 are you running?

The extension seems to be in the app directory rather than the vendor directory, did you install with composer?

Thanks

**Comment by ottybrad** [comment]
This was installed as per instructions

Sent from Mail for Windows 10

**Comment by cjgk** [comment]
Hi,

Could you please contact us through integrations@divido.com, we unfortunately can't monitor github issues for support errands.

Thanks
