### ISSUE TITLE
Price threshold not recognised correctly for products with customisable options

### ISSUE THREAD

**Issue by ollyand** [DividoFinancialServices/divido-magento2#17]
Steps to replicate:
Set 'Price threshold' to 500
Create a product with price of £299
Create customisable option; type:drop-down; option 1:£0; option 2:£50
Note this will create a product with a price from £299 to £349
View product page from frontend

Expected behaviour:
The Divido payment plans are not displayed.

Actual behaviour:
The Divido payment plans are shown

Example:
1.
https://mobilityscootersuk.co.uk/2007-rascal-liteway-3-4mph-transportable-electric-mobility-scooter.html

**Comment by JonnyCarter** [comment]
Fixed in commit  4b55a596b4abe5a7b
