### ISSUE TITLE
'Interest', 'Monthly Cost' & 'Total' overlapping on product frontend on iPad

### ISSUE THREAD

**Issue by ollyand** [DividoFinancialServices/divido-magento2#18]
Steps to replicate:
View a product page where the Divido plans are shown.
Set page width (using developer tools) to 768px (same as iPad) so that the items are displayed on one row
Product-secondary-column (right hand side) is enabled above 768px
Therefore product-primary-column (where Divido plans are shown) is limited to 285px wide

Expected result:
'Interest', 'Monthly Cost' & 'Total' are displayed on separate lines

Actual result:
'Interest', 'Monthly Cost' & 'Total' are displayed on the same line but are overlapping.

Notes:
It's like the breakpoint to switch from same line to separate lines is based on the overall page width and not the containing element size.

**Comment by JonnyCarter** [comment]
This has been fixed in the most recent version of the calculator
